# Generated by Django 5.0.1 on 2024-01-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoría', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='productos')),
                ('talla', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('temporada', models.CharField(max_length=20)),
                ('ocasión', models.CharField(max_length=20)),
                ('descripción', models.TextField()),
                ('stock', models.IntegerField()),
                ('disponibilidad', models.BooleanField()),
                ('fecha_creación', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualización', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
